// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Seizure.proto

package seizure

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type SeizureRequest struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer             *Client      `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	SeizureInformation   *SeizeInfo   `protobuf:"bytes,3,opt,name=seizureInformation,proto3" json:"seizureInformation,omitempty"`
	Product              *ProductName `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SeizureRequest) Reset()         { *m = SeizureRequest{} }
func (m *SeizureRequest) String() string { return proto.CompactTextString(m) }
func (*SeizureRequest) ProtoMessage()    {}
func (*SeizureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7441b94cd56365d9, []int{0}
}

func (m *SeizureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeizureRequest.Unmarshal(m, b)
}
func (m *SeizureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeizureRequest.Marshal(b, m, deterministic)
}
func (m *SeizureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeizureRequest.Merge(m, src)
}
func (m *SeizureRequest) XXX_Size() int {
	return xxx_messageInfo_SeizureRequest.Size(m)
}
func (m *SeizureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeizureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeizureRequest proto.InternalMessageInfo

func (m *SeizureRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SeizureRequest) GetCustomer() *Client {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *SeizureRequest) GetSeizureInformation() *SeizeInfo {
	if m != nil {
		return m.SeizureInformation
	}
	return nil
}

func (m *SeizureRequest) GetProduct() *ProductName {
	if m != nil {
		return m.Product
	}
	return nil
}

// The response message containing the greetings
type SeizureReply struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CodigoError          string   `protobuf:"bytes,2,opt,name=codigoError,proto3" json:"codigoError,omitempty"`
	MensajeError         string   `protobuf:"bytes,3,opt,name=mensajeError,proto3" json:"mensajeError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeizureReply) Reset()         { *m = SeizureReply{} }
func (m *SeizureReply) String() string { return proto.CompactTextString(m) }
func (*SeizureReply) ProtoMessage()    {}
func (*SeizureReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7441b94cd56365d9, []int{1}
}

func (m *SeizureReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeizureReply.Unmarshal(m, b)
}
func (m *SeizureReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeizureReply.Marshal(b, m, deterministic)
}
func (m *SeizureReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeizureReply.Merge(m, src)
}
func (m *SeizureReply) XXX_Size() int {
	return xxx_messageInfo_SeizureReply.Size(m)
}
func (m *SeizureReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SeizureReply.DiscardUnknown(m)
}

var xxx_messageInfo_SeizureReply proto.InternalMessageInfo

func (m *SeizureReply) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SeizureReply) GetCodigoError() string {
	if m != nil {
		return m.CodigoError
	}
	return ""
}

func (m *SeizureReply) GetMensajeError() string {
	if m != nil {
		return m.MensajeError
	}
	return ""
}

type Client struct {
	FirstName            string        `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName           string        `protobuf:"bytes,2,opt,name=middleName,proto3" json:"middleName,omitempty"`
	Surname              string        `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	LastSurname          string        `protobuf:"bytes,4,opt,name=lastSurname,proto3" json:"lastSurname,omitempty"`
	Document             *DocumentInfo `protobuf:"bytes,5,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_7441b94cd56365d9, []int{2}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Client) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Client) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Client) GetLastSurname() string {
	if m != nil {
		return m.LastSurname
	}
	return ""
}

func (m *Client) GetDocument() *DocumentInfo {
	if m != nil {
		return m.Document
	}
	return nil
}

type DocumentInfo struct {
	DocumentType         string   `protobuf:"bytes,1,opt,name=documentType,proto3" json:"documentType,omitempty"`
	DocumentNumber       string   `protobuf:"bytes,2,opt,name=documentNumber,proto3" json:"documentNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentInfo) Reset()         { *m = DocumentInfo{} }
func (m *DocumentInfo) String() string { return proto.CompactTextString(m) }
func (*DocumentInfo) ProtoMessage()    {}
func (*DocumentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7441b94cd56365d9, []int{3}
}

func (m *DocumentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentInfo.Unmarshal(m, b)
}
func (m *DocumentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentInfo.Marshal(b, m, deterministic)
}
func (m *DocumentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentInfo.Merge(m, src)
}
func (m *DocumentInfo) XXX_Size() int {
	return xxx_messageInfo_DocumentInfo.Size(m)
}
func (m *DocumentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentInfo proto.InternalMessageInfo

func (m *DocumentInfo) GetDocumentType() string {
	if m != nil {
		return m.DocumentType
	}
	return ""
}

func (m *DocumentInfo) GetDocumentNumber() string {
	if m != nil {
		return m.DocumentNumber
	}
	return ""
}

type ProductName struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	ProductState         string   `protobuf:"bytes,2,opt,name=productState,proto3" json:"productState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductName) Reset()         { *m = ProductName{} }
func (m *ProductName) String() string { return proto.CompactTextString(m) }
func (*ProductName) ProtoMessage()    {}
func (*ProductName) Descriptor() ([]byte, []int) {
	return fileDescriptor_7441b94cd56365d9, []int{4}
}

func (m *ProductName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductName.Unmarshal(m, b)
}
func (m *ProductName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductName.Marshal(b, m, deterministic)
}
func (m *ProductName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductName.Merge(m, src)
}
func (m *ProductName) XXX_Size() int {
	return xxx_messageInfo_ProductName.Size(m)
}
func (m *ProductName) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductName.DiscardUnknown(m)
}

var xxx_messageInfo_ProductName proto.InternalMessageInfo

func (m *ProductName) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *ProductName) GetProductState() string {
	if m != nil {
		return m.ProductState
	}
	return ""
}

type SeizeInfo struct {
	Concept              int32    `protobuf:"varint,1,opt,name=concept,proto3" json:"concept,omitempty"`
	SeizureType          int32    `protobuf:"varint,2,opt,name=seizureType,proto3" json:"seizureType,omitempty"`
	DebitForm            int32    `protobuf:"varint,3,opt,name=debitForm,proto3" json:"debitForm,omitempty"`
	ReceptionDate        string   `protobuf:"bytes,4,opt,name=receptionDate,proto3" json:"receptionDate,omitempty"`
	ProcessNumber        string   `protobuf:"bytes,5,opt,name=processNumber,proto3" json:"processNumber,omitempty"`
	Amount               int32    `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	City                 string   `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Address              string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	JudicialAccount      string   `protobuf:"bytes,9,opt,name=judicialAccount,proto3" json:"judicialAccount,omitempty"`
	Entity               string   `protobuf:"bytes,10,opt,name=entity,proto3" json:"entity,omitempty"`
	SeizureDate          string   `protobuf:"bytes,11,opt,name=seizureDate,proto3" json:"seizureDate,omitempty"`
	Plaintiff            *Client  `protobuf:"bytes,12,opt,name=plaintiff,proto3" json:"plaintiff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeizeInfo) Reset()         { *m = SeizeInfo{} }
func (m *SeizeInfo) String() string { return proto.CompactTextString(m) }
func (*SeizeInfo) ProtoMessage()    {}
func (*SeizeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7441b94cd56365d9, []int{5}
}

func (m *SeizeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeizeInfo.Unmarshal(m, b)
}
func (m *SeizeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeizeInfo.Marshal(b, m, deterministic)
}
func (m *SeizeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeizeInfo.Merge(m, src)
}
func (m *SeizeInfo) XXX_Size() int {
	return xxx_messageInfo_SeizeInfo.Size(m)
}
func (m *SeizeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SeizeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SeizeInfo proto.InternalMessageInfo

func (m *SeizeInfo) GetConcept() int32 {
	if m != nil {
		return m.Concept
	}
	return 0
}

func (m *SeizeInfo) GetSeizureType() int32 {
	if m != nil {
		return m.SeizureType
	}
	return 0
}

func (m *SeizeInfo) GetDebitForm() int32 {
	if m != nil {
		return m.DebitForm
	}
	return 0
}

func (m *SeizeInfo) GetReceptionDate() string {
	if m != nil {
		return m.ReceptionDate
	}
	return ""
}

func (m *SeizeInfo) GetProcessNumber() string {
	if m != nil {
		return m.ProcessNumber
	}
	return ""
}

func (m *SeizeInfo) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SeizeInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SeizeInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SeizeInfo) GetJudicialAccount() string {
	if m != nil {
		return m.JudicialAccount
	}
	return ""
}

func (m *SeizeInfo) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *SeizeInfo) GetSeizureDate() string {
	if m != nil {
		return m.SeizureDate
	}
	return ""
}

func (m *SeizeInfo) GetPlaintiff() *Client {
	if m != nil {
		return m.Plaintiff
	}
	return nil
}

func init() {
	proto.RegisterType((*SeizureRequest)(nil), "seizure.SeizureRequest")
	proto.RegisterType((*SeizureReply)(nil), "seizure.SeizureReply")
	proto.RegisterType((*Client)(nil), "seizure.Client")
	proto.RegisterType((*DocumentInfo)(nil), "seizure.DocumentInfo")
	proto.RegisterType((*ProductName)(nil), "seizure.ProductName")
	proto.RegisterType((*SeizeInfo)(nil), "seizure.SeizeInfo")
}

func init() { proto.RegisterFile("Seizure.proto", fileDescriptor_7441b94cd56365d9) }

var fileDescriptor_7441b94cd56365d9 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdd, 0x8e, 0xd3, 0x3c,
	0x10, 0xfd, 0xfa, 0xdf, 0x4c, 0x7f, 0x56, 0xb2, 0xbe, 0x85, 0x08, 0x21, 0x54, 0x45, 0x08, 0x55,
	0x42, 0x54, 0x62, 0x79, 0x82, 0x85, 0x82, 0xb4, 0x37, 0x0b, 0x4a, 0xb8, 0xe2, 0x2e, 0xb5, 0xa7,
	0xc8, 0xab, 0xc4, 0x0e, 0xb6, 0x83, 0x54, 0x1e, 0x81, 0xf7, 0xe1, 0x01, 0x78, 0x33, 0xe4, 0x9f,
	0xa4, 0xc9, 0xee, 0xde, 0x75, 0xce, 0x39, 0xe3, 0x99, 0x73, 0xdc, 0x18, 0x56, 0x19, 0xf2, 0x5f,
	0xb5, 0xc2, 0x5d, 0xa5, 0xa4, 0x91, 0x64, 0xa6, 0x7d, 0x99, 0xfc, 0x1d, 0xc0, 0x3a, 0x50, 0x29,
	0xfe, 0xa8, 0x51, 0x1b, 0xb2, 0x86, 0x21, 0x67, 0xf1, 0x60, 0x33, 0xd8, 0x4e, 0xd2, 0x21, 0x67,
	0xe4, 0x35, 0xcc, 0x69, 0xad, 0x8d, 0x2c, 0x51, 0xc5, 0xc3, 0xcd, 0x60, 0xbb, 0xb8, 0xba, 0xd8,
	0x85, 0xf6, 0xdd, 0x87, 0x82, 0xa3, 0x30, 0x69, 0x2b, 0x20, 0xef, 0x81, 0x04, 0xee, 0x46, 0x1c,
	0xa5, 0x2a, 0x73, 0xc3, 0xa5, 0x88, 0x47, 0xae, 0x8d, 0xb4, 0x6d, 0x76, 0xa2, 0x13, 0xa4, 0x8f,
	0xa8, 0xc9, 0x0e, 0x66, 0x95, 0x92, 0xac, 0xa6, 0x26, 0x1e, 0xbb, 0xc6, 0xff, 0xdb, 0xc6, 0x2f,
	0x1e, 0xbf, 0xcd, 0x4b, 0x4c, 0x1b, 0x51, 0xc2, 0x60, 0xd9, 0x5a, 0xa8, 0x8a, 0xd3, 0x03, 0x03,
	0x1b, 0x58, 0x50, 0xc9, 0xf8, 0x77, 0xf9, 0x51, 0x29, 0xe9, 0x3d, 0x44, 0x69, 0x17, 0x22, 0x09,
	0x2c, 0x4b, 0x14, 0x3a, 0xbf, 0x43, 0x2f, 0x19, 0x39, 0x49, 0x0f, 0x4b, 0xfe, 0x0c, 0x60, 0xea,
	0xed, 0x92, 0xe7, 0x10, 0x1d, 0xb9, 0xd2, 0x6e, 0x0d, 0x37, 0x27, 0x4a, 0xcf, 0x00, 0x79, 0x01,
	0x50, 0x72, 0xc6, 0x0a, 0x74, 0xb4, 0x9f, 0xd6, 0x41, 0x48, 0x0c, 0x33, 0x5d, 0x2b, 0x61, 0x49,
	0x3f, 0xa7, 0x29, 0xed, 0xa2, 0x45, 0xae, 0x4d, 0x16, 0xd8, 0xb1, 0x5f, 0xb4, 0x03, 0x91, 0xb7,
	0x30, 0x67, 0x92, 0xd6, 0x25, 0x0a, 0x13, 0x4f, 0x5c, 0x36, 0x97, 0x6d, 0x36, 0xfb, 0x40, 0xb8,
	0x5c, 0x5b, 0x59, 0xf2, 0x0d, 0x96, 0x5d, 0xc6, 0x7a, 0x6d, 0xb8, 0xaf, 0xa7, 0xaa, 0xd9, 0xbf,
	0x87, 0x91, 0x57, 0xb0, 0x6e, 0xea, 0xdb, 0xba, 0x3c, 0x60, 0x13, 0xda, 0x3d, 0x34, 0xf9, 0x0c,
	0x8b, 0xce, 0x8d, 0xd8, 0x5c, 0xc2, 0x9d, 0xdc, 0xec, 0x9b, 0x5c, 0x5a, 0xc0, 0x0e, 0x0e, 0x45,
	0x66, 0x72, 0xd3, 0x24, 0xd3, 0xc3, 0x92, 0xdf, 0x23, 0x88, 0xda, 0x3f, 0x87, 0x4d, 0x8a, 0x4a,
	0x41, 0xb1, 0x32, 0xe1, 0x36, 0x9b, 0xd2, 0x26, 0x15, 0x6c, 0x3b, 0x0f, 0x43, 0xc7, 0x76, 0x21,
	0xbb, 0x0b, 0xc3, 0x03, 0x37, 0x9f, 0xa4, 0x2a, 0x5d, 0xce, 0x93, 0xf4, 0x0c, 0x90, 0x97, 0xb0,
	0x52, 0x68, 0x4f, 0xe2, 0x52, 0xec, 0xed, 0x32, 0x3e, 0xeb, 0x3e, 0x68, 0x55, 0x95, 0x92, 0x14,
	0xb5, 0x0e, 0x29, 0x4c, 0xbc, 0xaa, 0x07, 0x92, 0x27, 0x30, 0xcd, 0x4b, 0x59, 0x0b, 0x13, 0x4f,
	0xdd, 0x98, 0x50, 0x11, 0x02, 0x63, 0xca, 0xcd, 0x29, 0x9e, 0xb9, 0x26, 0xf7, 0xdb, 0x3a, 0xca,
	0x19, 0x53, 0xa8, 0x75, 0x3c, 0xf7, 0x77, 0x1f, 0x4a, 0xb2, 0x85, 0x8b, 0xbb, 0x9a, 0x71, 0xca,
	0xf3, 0xe2, 0x9a, 0x52, 0x77, 0x5c, 0xe4, 0x14, 0xf7, 0x61, 0x3b, 0x0f, 0x85, 0xb1, 0x27, 0x83,
	0x13, 0x84, 0xaa, 0x93, 0x89, 0x73, 0xb4, 0xf0, 0xff, 0x9e, 0x0e, 0x44, 0xde, 0x40, 0x54, 0x15,
	0x39, 0x17, 0x86, 0x1f, 0x8f, 0xf1, 0xf2, 0xf1, 0x4f, 0xf9, 0xac, 0xb8, 0xca, 0xda, 0xa7, 0x21,
	0x43, 0xf5, 0x93, 0x53, 0x24, 0xd7, 0xb0, 0xe2, 0x42, 0xa3, 0x32, 0x01, 0x27, 0x4f, 0x7b, 0x9f,
	0xf4, 0xf9, 0x11, 0x79, 0x76, 0xf9, 0x90, 0xa8, 0x8a, 0x53, 0xf2, 0xdf, 0x61, 0xea, 0x1e, 0xa0,
	0x77, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94, 0x76, 0xb0, 0x62, 0x91, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SeizureServiceClient is the client API for SeizureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SeizureServiceClient interface {
	// Sends a greeting
	InsertSeizure(ctx context.Context, in *SeizureRequest, opts ...grpc.CallOption) (*SeizureReply, error)
}

type seizureServiceClient struct {
	cc *grpc.ClientConn
}

func NewSeizureServiceClient(cc *grpc.ClientConn) SeizureServiceClient {
	return &seizureServiceClient{cc}
}

func (c *seizureServiceClient) InsertSeizure(ctx context.Context, in *SeizureRequest, opts ...grpc.CallOption) (*SeizureReply, error) {
	out := new(SeizureReply)
	err := c.cc.Invoke(ctx, "/seizure.SeizureService/insertSeizure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeizureServiceServer is the server API for SeizureService service.
type SeizureServiceServer interface {
	// Sends a greeting
	InsertSeizure(context.Context, *SeizureRequest) (*SeizureReply, error)
}

// UnimplementedSeizureServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSeizureServiceServer struct {
}

func (*UnimplementedSeizureServiceServer) InsertSeizure(ctx context.Context, req *SeizureRequest) (*SeizureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertSeizure not implemented")
}

func RegisterSeizureServiceServer(s *grpc.Server, srv SeizureServiceServer) {
	s.RegisterService(&_SeizureService_serviceDesc, srv)
}

func _SeizureService_InsertSeizure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeizureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeizureServiceServer).InsertSeizure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seizure.SeizureService/InsertSeizure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeizureServiceServer).InsertSeizure(ctx, req.(*SeizureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeizureService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seizure.SeizureService",
	HandlerType: (*SeizureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "insertSeizure",
			Handler:    _SeizureService_InsertSeizure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Seizure.proto",
}
