apiVersion: v1
kind: Service
metadata:
  labels:
    country: argentina
    role: domain
    domain: customer
    app:  customer
  name: obtener-cliente-dom-svc
spec:
  ports:
    - name: http
      port: 50001
      targetPort: 50001
  selector:
    country: argentina
    role: domain
    domain: customer
    app: customer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: obtener-cliente-dom-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        country: argentina
        role: domain
        domain: customer
        app: customer
    spec:
      imagePullSecrets:
        - name: obtener-cliente-dom
      containers:
        - name: obtener-cliente-dom
          image: lgaete/obtener-cliente-dom:25a3a8b
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app/config
              name: obtener-cliente-dom-configmap
          ports:
            - name: http
              containerPort: 50001
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 50001
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: obtener-cliente-dom-configmap
          configMap:
            name: obtener-cliente-dom-configmap
            items:
              - key: config
                path:  config.yml

