// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "corp/fif/inte/customers/internal/core/entity"
import mock "github.com/stretchr/testify/mock"

// CustomerUseCase is an autogenerated mock type for the CustomerUseCase type
type CustomerUseCase struct {
	mock.Mock
}

// FindCustomer provides a mock function with given fields: documentNumber, documentType, country
func (_m *CustomerUseCase) FindCustomer(documentNumber string, documentType string, country string) (*entity.Customer, error) {
	ret := _m.Called(documentNumber, documentType, country)

	var r0 *entity.Customer
	if rf, ok := ret.Get(0).(func(string, string, string) *entity.Customer); ok {
		r0 = rf(documentNumber, documentType, country)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(documentNumber, documentType, country)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
