// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	seizure "Seizuresss/internal/seizure"

	mock "github.com/stretchr/testify/mock"
)

// SeizureUseCase is an autogenerated mock type for the SeizureUseCase type
type SeizureUseCase struct {
	mock.Mock
}

// SeizureCreate provides a mock function with given fields: _a0
func (_m *SeizureUseCase) SeizureCreate(_a0 seizure.Seizures) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(seizure.Seizures) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
