// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "sizesure/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// SeizureRepository is an autogenerated mock type for the SeizureRepository type
type SeizureRepository struct {
	mock.Mock
}

// AddSeizures provides a mock function with given fields: ctx, seizure
func (_m *SeizureRepository) AddSeizures(ctx context.Context, seizure entity.Seizure) (entity.SeizureResp, error) {
	ret := _m.Called(ctx, seizure)

	var r0 entity.SeizureResp
	if rf, ok := ret.Get(0).(func(context.Context, entity.Seizure) entity.SeizureResp); ok {
		r0 = rf(ctx, seizure)
	} else {
		r0 = ret.Get(0).(entity.SeizureResp)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.Seizure) error); ok {
		r1 = rf(ctx, seizure)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
