// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import customer "corp/fif/inte/customers/internal/core/repository/find_customer/proto"

import mock "github.com/stretchr/testify/mock"

// ClientesServiceClient is an autogenerated mock type for the ClientesServiceClient type
type FindCustomerServiceClient struct {
	mock.Mock
}

// ObtenerInfoCliente provides a mock function with given fields: ctx, in, opts
func (_m *FindCustomerServiceClient) FindCustomer(ctx context.Context, in *customer.FindRequest) (*customer.Customer, error) {
	ret := _m.Called(ctx, in)

	var r0 *customer.Customer
	if rf, ok := ret.Get(0).(func(context.Context, *customer.FindRequest) *customer.Customer); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *customer.FindRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
